name: Danger
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - name: GitHub Action for Danger-Swift + SwiftLint
      - uses: 417-72KI/danger-swiftlint@v1.0.1
      - uses: actions/checkout@v2
      - name: Danger
        uses: danger/swift@3.0.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
